use_frameworks!

target 'NoStoryboard_Example' do
  pod 'NoStoryboard', :path => '../'

  target 'NoStoryboard_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
